### ISSUE TITLE
'Missing number, treated as zero' when dividing polynomials with remainder zero

### ISSUE THREAD

**Issue by ariymarkowitz** [loopspace/Polynomial-division#1]
When diving a polynomial by another with remainder zero, compiling results in an infinite loop of 'Missing number, treated as zero' errors. This occurs with any base.

**Comment by loopspace** [comment]
Thanks for the report.  Can you check the latest version and see if it fixes it for you?

**Comment by ariymarkowitz** [comment]
It works! Thanks 😄
